name: zaoed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  glass: ^1.0.2+1
  glassmorphism_ui: ^0.3.0
  pinput: ^3.0.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
  fonts:
    - family: SfArabic
      fonts:
        - asset: fonts/SFArabic-Regular.ttf
