name: zaoed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dashed_stepper: ^0.0.4
  easy_stepper: ^0.8.3
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  glass: ^1.0.2+1
  glassmorphism_ui: ^0.3.0
  image_picker: ^1.0.5
  lottie: ^2.7.0
  pinput: ^3.0.1
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.0.2
  syncfusion_flutter_charts: ^24.1.41
  syncfusion_flutter_gauges: ^24.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets//lottie/
  fonts:
    - family: SfArabic
      fonts:
        - asset: fonts/SFArabic-Regular.ttf
